### ISSUE TITLE
PCOIP will not connect.

### ISSUE THREAD

**Issue by queglay** [aws-quickstart/quickstart-cloudvideoediting#2]
After the stack has completed and I have retrieved the password, I cannot connect successfully with teradici PCOIP client on macos.  I get-

Error Unable to connect to (public ipv4 address of the edit host)
Please enter a new name or IP address.

I have the correct ipv4 address for the edit host to be entered into the pcoip software, and I have enabled the rdp gateway to access my ip adress during the installation procedure.

**Comment by zoomerkind** [comment]
I was just looking at the deployment via CloudFormation.  It doesn’t look like you had the choice to set a CIDR range for access to the edit host.  I will get this fixed.


  1.  If you go to the ec2 console and click your edit host, then scroll down in the detailed info until you see “Security groups”.
  2.  You’ll see one named editHostSecurityGroup-xxxxx.  Click that one (not the inbound rules link).
  3.  It takes you to ec2->Security Groups with the security group above selected.
     *   Then click the “Inbound tab”
     *   Click “Edit” and for each rule:

                                                               i.      Under source dropdown select “My IP”

                                                             ii.      Click Save

Note that if you go somewhere else (home vs work) and try and remote in, it won’t let you.   This is because you selected a single IP in the 3b above.  You can type in a CIDR range if you know that instead by selecting the “Custom” dropdown

Let me know if that works.

**Comment by zoomerkind** [comment]
We may have some steps wrong in the quickstart guide.  Try this:

1. Remote in with a Windows RDP client.  You will have to follow the steps on decrypting the windows password.
2. Go back to step 6 and continue along
