### ISSUE TITLE
Is the RDGW instace (set as t2 in my case) able to be stopped?

### ISSUE THREAD

**Issue by queglay** [aws-quickstart/quickstart-cloudvideoediting#3]
I have had problems trying to stop the g3 edit instance - it just keeps restarting after it is stopped or terminated.

The T2 RDGW instance seems to do the same thing.

**Comment by zoomerkind** [comment]
This is because it’s in an auto scaling group.  To properly shutdown all the infrastructure that the Quick Start spun up, go back to the CloudFormation console.  Click on the stack named Cloud-Video-Editing and then click Actions->Delete Stack.

It will complain if you have deleted infrastructure out from under CloudFormation.

**Comment by queglay** [comment]
Thanks i deleted the stacks.  I have a suggestion, It would be great if there was some faster alternative to stopping and starting rather than fireing up the whole stack again and waiting 30 minutes to complete.  The high powered edit hosts aren't cheap to leave running all the time which i was doing a lot this week.

Thanks for all your work in helping with this project, its great to see what's possible.

**Comment by vsnyc** [comment]
@queglay Apologies for replying late on this. For future reference, you can set the desired capacity to zero in the autoscaling group to prevent it from creating new instances. You don't necessarily have to delete the stack.

![Screen Shot 2019-05-08 at 1 52 32 PM](https://user-images.githubusercontent.com/624297/57396746-13584e00-7199-11e9-8f2a-0b8d447bbec3.png)
