### ISSUE TITLE
Deployment Guide Doesn't Include Bastion Host Instructions 

### ISSUE THREAD

**Issue by smp** [aws-quickstart/quickstart-cloudvideoediting#4]
Step 5 from the deployment guide has you connect directly to the edit host, but then why is there a bastion host? Additionally, it doesn't seem that I can connect to the edit host from the bastion host.

**Comment by smp** [comment]
Also, page 17 states "The Edit Host instance is in a public subnet..." is this really the case?

**Comment by vsnyc** [comment]
Hi Shawn, thanks for the feedback. The instructions in Step 5 do work both for Edit host and bastion host. Looking closely and comparing with a similar [VFX Workstations quick start](https://github.com/aws-quickstart/quickstart-vfx-workstation-windows/blob/master/templates/cloud-vfx-workstation.template#L439), and it's [guide](https://aws-quickstart.s3.amazonaws.com/quickstart-vfx-workstation-windows/doc/visual-effects-workstations-on-the-aws-cloud.pdf), see page 4, step 4; I can see that join domain configuration is missing in this quick start hence you are having issues connecting from RDP host to Edit host. 

I have verified that once you fetch the Administrator password as described in Step 5, you should be able to RDP into the Edit host from RDGW host using the `private IP of the Edit host`, the `Administrator user` and `password`, but not the `example\Admin` user. I'll work on updating the boostrap, once I update the config to include `joinDomain` command, the instructions to login will become a bit simplified.

As to why the Edit Host is in the public subnet, it is intended to be used as a workstation that you would access from your device, e.g., on the corp network using the Teradici PCoIP client. That's why the instance is placed in the public subnet and port 4172 and 443 is opened to the EditHostAccessCIDR.

RDGW host still has it's purpose; for example, 
a) if you had to manage the Edit host, since RDP 3389 port isn't opened to the EditHostAccessCIDR
b) if you added any other infrastructure into the VPC in future and needed a jump host to manage that.

**Comment by vsnyc** [comment]
Login instructions have been updated in [latest guide](https://fwd.aws/4A4Ab)
